services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nc
    ports:
      - "5432:5432"
    volumes:
      - nc_pg:/var/lib/postgresql/data

volumes:
  nc_pg:

